name: Test `wasm_runtime.so`

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./wasm_runtime
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./wasm_runtime
      run: cargo test --verbose
